# Generated by Django 3.0.4 on 2020-03-31 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
