# Generated by Django 3.0.4 on 2020-04-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0004_auto_20200401_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='contact',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='contact',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
