# Generated by Django 3.0.4 on 2020-04-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0006_item_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.FloatField(),
        ),
    ]
