# Generated by Django 3.0.4 on 2020-04-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0008_auto_20200402_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
        migrations.RemoveField(
            model_name='image',
            name='location',
        ),
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
        migrations.AddField(
            model_name='post',
            name='label',
            field=models.CharField(choices=[('p', 'Primary'), ('S', 'Secondary'), ('D', 'Danger')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('B', 'Bed'), ('C', 'Chair'), ('T', 'Table')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
