# Generated by Django 3.0.4 on 2020-04-02 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0009_auto_20200402_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='label',
        ),
    ]
