# Generated by Django 3.0.4 on 2020-04-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0010_auto_20200402_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('B', 'Bed'), ('C', 'Chair'), ('T', 'Table')], default='S', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('p', 'Primary'), ('S', 'Secondary'), ('D', 'Danger')], default='P', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('B', 'Bed'), ('C', 'Chair'), ('T', 'Table')], default='p', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='label',
            field=models.CharField(choices=[('p', 'Primary'), ('S', 'Secondary'), ('D', 'Danger')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
