# Generated by Django 3.0.4 on 2020-04-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0011_auto_20200402_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
