# Generated by Django 3.0.4 on 2020-04-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0012_auto_20200402_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
