# Generated by Django 3.0.4 on 2020-04-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0013_post_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
