# Generated by Django 3.0.4 on 2020-04-02 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0014_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderPost',
        ),
    ]
