# Generated by Django 3.0.4 on 2020-04-02 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0015_auto_20200402_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='posts',
        ),
        migrations.RemoveField(
            model_name='orderpost',
            name='item',
        ),
        migrations.AddField(
            model_name='orderpost',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bizz.Post'),
            preserve_default=False,
        ),
    ]
