# Generated by Django 3.0.4 on 2020-04-02 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0016_auto_20200402_1206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
