# Generated by Django 3.0.4 on 2020-04-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0017_delete_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
