# Generated by Django 3.0.4 on 2020-04-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
